# Generated by Django 5.2 on 2025-05-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.BigIntegerField()),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('timezones', models.JSONField(default=list)),
                ('languages', models.JSONField(default=dict)),
                ('flag_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
