# Generated by Django 5.2 on 2025-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalBloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('official_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('ccn3', models.CharField(blank=True, max_length=3, null=True)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('independent', models.BooleanField(default=True)),
                ('un_member', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('start_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('capital_latlng', models.JSONField(blank=True, null=True)),
                ('alt_spellings', models.JSONField(blank=True, null=True)),
                ('tld', models.JSONField(blank=True, null=True)),
                ('timezones', models.JSONField(blank=True, null=True)),
                ('car_signs', models.JSONField(blank=True, null=True)),
                ('car_side', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('flag_svg', models.URLField(blank=True, null=True)),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, null=True)),
                ('gini', models.JSONField(blank=True, null=True)),
                ('postal_code', models.JSONField(blank=True, null=True)),
                ('borders', models.ManyToManyField(blank=True, to='countries.country')),
                ('currencies', models.ManyToManyField(blank=True, to='countries.currency')),
                ('languages', models.ManyToManyField(blank=True, to='countries.language')),
                ('regional_blocs', models.ManyToManyField(blank=True, to='countries.regionalbloc')),
            ],
        ),
    ]
