# Generated by Django 5.2 on 2025-05-04 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name_common',
        ),
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='borders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='cca3',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='ccn3',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='cioc',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='continents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='demonyms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='gini',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='independent',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='landlocked',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='latlng',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='maps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_official',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='un_member',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='cca2',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
